//created on: 2016-01-09
package starWars

//list any import classes here.
import starWars.Question;
import javax.swing.*;

//declare any global variables here
/*
proponowani "bohaterowie":
Anakin Skywalker / Darth Vader
Luke Skywalker
Obi-wan Kenobi
Yoda
Leia Organa
Han Solo
Chewbacca
R2-D2
C3-PO
BB8 (sw7)
Rei (sw7)
Finn (sw7)
Kylo Ren (sw7)
Boba Fett
Padme Amidala
Jabba
Darth Maul
Darth Sidious
Lando Calrissian
Count Dooku
Qui-gon Jinn
Jar-jar Binks
Grievous
Mace Windu
*/

rule "R2D2"
	salience 1000000
	when
		Fact(type == "robot", value == "Tak")
		Fact(type == "rozmiar", value == "Niski")
		Fact(type == "bron", value == "Inna")
		Fact(type == "poruszanie", value == "Jezdzi")
		Fact(type == "kolor_robota", value == "Niebieski")
	then
		JOptionPane.showMessageDialog(null, "Postaæ o której pomyœla³eœ to: " + drools.getRule().getName() + "!", "StarWars", JOptionPane.INFORMATION_MESSAGE);
		System.exit(0);
end;

rule "BB8"
	salience 1000000
	when
		Fact(type == "robot", value == "Tak")
		Fact(type == "rozmiar", value == "Niski")
		Fact(type == "bron", value == "Inna")
		Fact(type == "poruszanie", value == "Jezdzi")
		Fact(type == "kolor_robota", value == "Pomaranczowy")
	then
		JOptionPane.showMessageDialog(null, "Postaæ o której pomyœla³eœ to: " + drools.getRule().getName() + "!", "StarWars", JOptionPane.INFORMATION_MESSAGE);
		System.exit(0);
end;

rule "C3PO"
	salience 1000000
	when
		Fact(type == "robot", value == "Tak")
		Fact(type == "rozmiar", value == "Wysoki")
		Fact(type == "bron", value == "Brak")
		Fact(type == "poruszanie", value == "Chodzi")
	then
		JOptionPane.showMessageDialog(null, "Postaæ o której pomyœla³eœ to: " + drools.getRule().getName() + "!", "StarWars", JOptionPane.INFORMATION_MESSAGE);
		System.exit(0);
end;

rule "Jabba"
	salience 1000000
	when
		Fact(type == "zywa_istota", value == "Tak")
		Fact(type == "bron", value == "Brak")
		Fact(type == "poruszanie", value == "Suwa sie")
		Fact(type == "rozmiar", value != "Niski")
		(Fact(type == "plec", value != "Obojnak")
		or
		Fact(type == "plec", value != "Niewiadomo"))
		Fact(type == "kolor_wlosow", value == "Nie ma")
	then
		JOptionPane.showMessageDialog(null, "Postaæ o której pomyœla³eœ to: " + drools.getRule().getName() + "!", "StarWars", JOptionPane.INFORMATION_MESSAGE);
		System.exit(0);
end;

rule "Yoda"
	salience 1000000
	when
		(
			Fact(type == "zywa_istota", value == "Tak")
			and
			Fact(type == "rozmiar", value == "Niski")
			and
			Fact(type == "kolor_postaci", value == "Zielony")
		) or (
			(
				Fact(type == "bron", value == "Miecz Swietlny")
				and
				Fact(type == "kolor_miecza", value =="Zielony")
			) or (
				Fact(type == "jedi", value == "Tak")
			)
			and
			Fact(type == "kolor_postaci", value == "Zielony")
		)
		
	then
		JOptionPane.showMessageDialog(null, "Postaæ o której pomyœla³eœ to: " + drools.getRule().getName() + "!", "StarWars", JOptionPane.INFORMATION_MESSAGE);
		System.exit(0);
end;

rule "Han Solo"
	salience 1000000
	when
		Fact(type=="zabity_przez_syna", value == "Tak")
	then
		JOptionPane.showMessageDialog(null, "Postaæ o której pomyœla³eœ to: " + drools.getRule().getName() + "!", "StarWars", JOptionPane.INFORMATION_MESSAGE);
		System.exit(0);
end;

rule "Kylo Ren"
	salience 1000000
	when
		Fact(type=="bron", value=="Miecz Swietlny")
		Fact(type=="kolor_miecza", value=="Czerwony")
	then
		JOptionPane.showMessageDialog(null, "Postaæ o której pomyœla³eœ to: " + drools.getRule().getName() + "!", "StarWars", JOptionPane.INFORMATION_MESSAGE);
		System.exit(0);
end;