//created on: 2016-01-02
package starWars

//list any import classes here.
import starWars.Question;
import javax.swing.*;

//declare any global variables here


rule "start"
	salience 1000
	when
       
    then
	Fact o = Question.Ask("like_me");
	insert(o);
end


rule "lubie_cie"
    when
        Fact(type=="lubienie", value=="Tak")
    then
    	JOptionPane.showMessageDialog(null, "Te¿ Ciê lubiê.", "Wynik", JOptionPane.INFORMATION_MESSAGE);
    	insert(Question.Ask("int_value"));

end

rule "nie_lubie_cie"
	when
		Fact(type=="lubienie", value=="Nie")
	then
		JOptionPane.showMessageDialog(null, "Spierdalaj.", "Wynik", JOptionPane.INFORMATION_MESSAGE);
end

rule "dobry_int"
	when
		Fact(type=="test_inta", value==3)
	then
		JOptionPane.showMessageDialog(null, "Sczytany int = 3.", "Wynik", JOptionPane.INFORMATION_MESSAGE);
end

rule "zly_int"
	when
		Fact(type=="test_inta", value!=3)
	then
		JOptionPane.showMessageDialog(null, "Ciota, zly int.", "Wynik", JOptionPane.INFORMATION_MESSAGE);
end
